source("R/00_setup.R")
nowcast <- readRDS(file.path(DOSSIER_RESULTATS, "nowcast_midas.rds"))
backtest <- readRDS(file.path(DOSSIER_RESULTATS, "backtest_midas.rds"))
midas <- readRDS(file.path(DOSSIER_RESULTATS, "midas_resultats.rds"))

cat("\n\n============================================================\n")
cat("        SYNTHESE FINALE -- Methode MIDAS\n")
cat("============================================================\n\n")
cat(sprintf("1) NOWCAST DU PIB (prochain trimestre) : %+.2f %%\n", nowcast$croissance_pib * 100))
cat(sprintf("\n2) VALIDATION HORS ECHANTILLON (%d trimestres) :\n", length(backtest$dates_test)))
cat(sprintf("   RMSFE MIDAS        : %.4f\n", backtest$rmsfe_modele))
cat(sprintf("   RMSFE repere AR(2) : %.4f\n", backtest$rmsfe_ar2))
cat(sprintf("   Diebold-Mariano p-value : %.3f\n", backtest$test_dm$p.value))
cat("\n3) METHODE PAR BRANCHE :\n")
for (b in names(midas)) cat(sprintf("   %-28s %s\n", b, midas[[b]]$methode))
cat("\n============================================================\n")
